// <auto-generated />
using System;
using HogwartsRunningClub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HogwartsRunningClub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HogwartsRunningClub.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("TopicId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("CommentId");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("HogwartsRunningClub.Models.House", b =>
                {
                    b.Property<int>("HouseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<double>("TotalMiles");

                    b.HasKey("HouseId");

                    b.ToTable("House");

                    b.HasData(
                        new { HouseId = 1, Description = "Gryffindor House is named after Hogwarts Founder Godric Gryffindor and is home to young witchs and wizards that model exemplary courage, bravery, and nerve!", Title = "Gryffindor", TotalMiles = 0.0 },
                        new { HouseId = 2, Description = "Hufflepuff House is named after Hogwarts Founder Helga Hufflepuff and is home to young witchs and wizards that model honesty, loyalty, justice, and patience!", Title = "Hufflepuff", TotalMiles = 0.0 },
                        new { HouseId = 3, Description = "Ravenclaw House is named after Hogwarts Founder Rowena Ravenclaw and is home to young witchs and wizards that model exemplary intelligence, creativity, wit, and learning!", Title = "Ravenclaw", TotalMiles = 0.0 },
                        new { HouseId = 4, Description = "Slytherin House is named after Hogwarts Founder Salazar Slytherin and is home to young witchs and wizards that model ambition, cunning, shrewdness, and self-preservation!", Title = "Slytherin", TotalMiles = 0.0 }
                    );
                });

            modelBuilder.Entity("HogwartsRunningClub.Models.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CharityDescription")
                        .IsRequired();

                    b.Property<string>("CharityName")
                        .IsRequired();

                    b.Property<double>("Distance");

                    b.Property<string>("MedalImage");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("RaceId");

                    b.ToTable("Race");

                    b.HasData(
                        new { RaceId = 1, CharityDescription = "Since its founding in 1947, Dana-Farber Cancer Institute in Boston, Massachusetts has been committed to providing adults and children with cancer with the best treatment available today while developing tomorrow's cures through cutting-edge research.", CharityName = "The Dana-Farber Cancer Institute / Jimmy Fund", Distance = 3.1, Title = "Sorcerer's Stone 5k" },
                        new { RaceId = 2, CharityDescription = "Since its founding in 1947, Dana-Farber Cancer Institute in Boston, Massachusetts has been committed to providing adults and children with cancer with the best treatment available today while developing tomorrow's cures through cutting-edge research.", CharityName = "The Dana-Farber Cancer Institute / Jimmy Fund", Distance = 6.2, Title = "Chamber of Secrets 10k" },
                        new { RaceId = 3, CharityDescription = "Since its founding in 1947, Dana-Farber Cancer Institute in Boston, Massachusetts has been committed to providing adults and children with cancer with the best treatment available today while developing tomorrow's cures through cutting-edge research.", CharityName = "The Dana-Farber Cancer Institute / Jimmy Fund", Distance = 3.1, Title = "A Walk In the Moonlight 5k" },
                        new { RaceId = 4, CharityDescription = "Since its founding in 1947, Dana-Farber Cancer Institute in Boston, Massachusetts has been committed to providing adults and children with cancer with the best treatment available today while developing tomorrow's cures through cutting-edge research.", CharityName = "The Dana-Farber Cancer Institute / Jimmy Fund", Distance = 3.1, Title = "Hedwig Memorial Run 5k" },
                        new { RaceId = 5, CharityDescription = "Since its founding in 1947, Dana-Farber Cancer Institute in Boston, Massachusetts has been committed to providing adults and children with cancer with the best treatment available today while developing tomorrow's cures through cutting-edge research.", CharityName = "The Dana-Farber Cancer Institute / Jimmy Fund", Distance = 6.06, Title = "Platform 9 3/4k Year One" },
                        new { RaceId = 6, CharityDescription = "Since its founding in 1947, Dana-Farber Cancer Institute in Boston, Massachusetts has been committed to providing adults and children with cancer with the best treatment available today while developing tomorrow's cures through cutting-edge research.", CharityName = "The Dana-Farber Cancer Institute / Jimmy Fund", Distance = 18.64, Title = "Triwizard Challenge 5k/10k/15k" },
                        new { RaceId = 7, CharityDescription = "Since its founding in 1947, Dana-Farber Cancer Institute in Boston, Massachusetts has been committed to providing adults and children with cancer with the best treatment available today while developing tomorrow's cures through cutting-edge research.", CharityName = "The Dana-Farber Cancer Institute / Jimmy Fund", Distance = 3.1, Title = "Deathly Hallows Challenge" },
                        new { RaceId = 8, CharityDescription = "An Atlanta-based running organization that raises awareness of CF, sponsors CF research, and directly supports local families dealing with this terrible disease. Their youth organization, Rosebuds, is a youth running club founded by a brave little girl named Elana with the theme of “Kids helping kids with CF.", CharityName = "Miles for Cystic Fibrosis", Distance = 3.1, Title = "Dementor's Kiss 5k" },
                        new { RaceId = 9, CharityDescription = "An awesome charity that connects military members with loving foster homes to care for their pets when they have to deploy overseas. They also provide financial assistance for emergency medical services for military pets.", CharityName = "Dogs on Deployment", Distance = 3.1, Title = "Weasley’s Wizarding Wheezer 5k" },
                        new { RaceId = 10, CharityDescription = "An incredible organization with one simple mission: To enable people with all types of disabilities to participate in mainstream athletics in order to promote personal achievement, enhance self esteem, and lower barriers to living a fulfilling life. Whether it’s supplying racing wheelchairs to athletes or connecting a guide with a vision-impaired runner, Achilles International ensures that an athlete’s disability doesn't limit their potential.", CharityName = "Achilles International", Distance = 5.0, Title = "Voldemort V-Miler" },
                        new { RaceId = 11, CharityDescription = "A Florida-based group of firefighters, police officers and EMTs who ride bicycles to honor those who have died in the line of duty. These volunteers ride hundreds of miles on or near the anniversary of the honoree’s ultimate sacrifice to remind the families, friends, and the community of the fallen that they are not forgotten. The result of their rides, and this event, were donations made directly to the families of those who gave their lives to protect the rest of us.", CharityName = "Brotherhood Ride", Distance = 3.88, Title = "Dept. of Mysteries 6.2442k" },
                        new { RaceId = 12, CharityDescription = "Accio Books! is the Harry Potter Alliance’s annual book drive and since 2009, Harry Potter fans around the world have donated more than 350,000 books to underprivileged or under-served readers.", CharityName = "Harry Potter Alliance Accio Books! Campaign", Distance = 6.06, Title = "Platform 9 3/4k Year Two" },
                        new { RaceId = 13, CharityDescription = "A family support program which pays travel expenses for families whose children are undergoing clinical trials for the NOAH Protocol, a revolutionary new treatment for pediatric brain cancer!", CharityName = "Noah’s Light Foundation's Noah's Gifts", Distance = 3.1, Title = "Patronus 5k" },
                        new { RaceId = 14, CharityDescription = "All Proceeds from the Marauder's Challenge were divided up evenly amongst all HRC 2015 Charity partners!", CharityName = "2015", Distance = 3.1, Title = "Marauder’s Challenge" },
                        new { RaceId = 15, CharityDescription = "Their mission is to provide anyone in need with a warm coat, free of charge. Your support helped their efforts organizing more than 3,000 coat drives each year and purchasing brand new coats for kids in need.", CharityName = "One Warm Coat", Distance = 3.1, Title = "The Molly Weasley Ugly Jumper Run" },
                        new { RaceId = 16, CharityDescription = "They provide abused, neglected, and abandoned children entering foster care, with little or no belongings, a My Stuff Bag — an individual duffel bag filled with brand new childhood necessities. HRC helped My Stuff Bags send their 500,000th bag to a child in need!", CharityName = "My Stuff Bags Foundation", Distance = 8.08, Title = "Umbridge Run 13k" },
                        new { RaceId = 17, CharityDescription = "A team of runners dedicated to defeating pancreatic cancer, raising awareness, and supporting patients and families affected by this terrible disease that kills more than 80% of those diagnosed.", CharityName = "Project Purple", Distance = 20.92, Title = "The Half-Blood Prince Half Marathon" },
                        new { RaceId = 18, CharityDescription = "The Gryffindor 21k will help Big Cat Rescue in Tampa, Florida, build a new bobcat rehabilitation facility that minimizes human contact so these big cats can return to the wild. The Ravenclaw 10k will help International Bird Rescue in San Francisco, California, build a new aviary to help save birds who are the victims of oil spills and natural disasters. The Slytherin 6k will help Friends of Scales Reptile Rescue outside of Chicago, Illinois, build their reptile rescue facility and provide life - saving veterinary care for abandoned and injured snakes, turtles, and other reptiles. The Hufflepuff 5k will help the Save Me Trust outside of London, England, organize three teams in Southern England to catch, vaccinate and release badgers to stop the spread of bovine tuberculosis and, more importantly, stop the Badger Cull which has killed thousands of badgers.", CharityName = "Big Cat Rescue, International Bird Rescue, Friends of Scales Reptile Rescue, Save Me Trust", Distance = 26.1, Title = "The #OneHRC House Marathon" },
                        new { RaceId = 19, CharityDescription = "While some beasts are fantastic, others are not. Currently, more than 1 billion people around the globe, half of which are children, suffer from seven “neglected tropical diseases” (NTDs). Your participation will support the End7 campaign to rid the developing world of these seven parasitic diseases and end the suffering of over a half a billion suffering children. With your help, we targeted these parasitic “beasts” in at least three post-Ebola countries in West Africa.", CharityName = "End7", Distance = 3.1, Title = "Fantastic Beast 5k" },
                        new { RaceId = 20, CharityDescription = "Carry the Future provides infant and toddler carriers to mothers and fathers fleeing war-ravaged regions simply looking for safety for their families. They have donated thousands of carriers and countless aid items to date, and they have a team of volunteers on the ground living near the refugee camps to ensure that they have a constant presence and are aware of immediate needs.", CharityName = "Carry The Future", Distance = 6.06, Title = "Platform 9 3/4k Year Three" },
                        new { RaceId = 21, CharityDescription = "The King's Cross Challenge supports all 2016 charity partners, with proceeds from this medal being divided evenly amongst them!", CharityName = "HRC 2016 Charity Partners", Distance = 3.1, Title = "King's Cross Challenge" },
                        new { RaceId = 22, CharityDescription = "Limbs for Life Foundation is a global nonprofit organization dedicated to providing fully-functional prosthetic care for individuals who cannot otherwise afford it and raising awareness of the challenges facing amputees. When a person becomes an amputee, they are faced with staggering emotional and financial lifestyle changes.  Fortunately, high tech prosthetic devices that restore a person’s basic skills and independence are available. Unfortunately, many amputees lack the financial resources to obtain adequate prosthetic care. Limbs for Life Foundation steps in to provide a financial bridge between low-income amputees and the quality prosthetic care needed to restore their lives.", CharityName = "Limbs for Life Foundation", Distance = 3.1, Title = "Constant Vigilance 5k" },
                        new { RaceId = 23, CharityDescription = "Hermione just wanted to do some good in the world. She was determined to make life better for House Elves working in Hogwarts Castle, and throughout the wizarding world. Her compassion for their well-being and her support of their freedom demonstrated her leadership abilities, and led to the elves joining in the fight to defend Hogwarts in the final battle of the Wizarding War. It is in this spirit that proceeds from this event went to support the Harry Potter Alliance and their Granger Leadership Academy. The Harry Potter Alliance (HPA) believes that the world needs more Hermione Grangers, and we emphatically agree.", CharityName = "Harry Potter Alliance (HPA)", Distance = 6.2, Title = "The 10K and S.P.E.W." },
                        new { RaceId = 24, CharityDescription = "a charity dedicated to presenting hope and finding help for people struggling with depression, addiction, self-injury, and suicide. TWLOHA exists to encourage, inform, inspire, and also to invest directly into treatment and recovery.", CharityName = "To Write Love On Her Arms", Distance = 6.2, Title = "Unmasked 10-Mile Run For Your Life" },
                        new { RaceId = 25, CharityDescription = "MK9R’s mission is to rescue, reunite, re-home, rehabilitate, and repair any retired working dog that has served mankind in some capacity. They believe these heroic canines have earned and deserve a good retirement, a loving home, and lifelong care. They provide retiring working dog heroes with transport, adoption facilitation, rehoming, financial assistance for life threatening medical situations, and end-of-life benefits which are currently lacking when these dogs retire after serving their country and their communities.", CharityName = "Mission K9 Rescue", Distance = 13.1, Title = "Sirius Half Marathon" },
                        new { RaceId = 26, CharityDescription = "If you think a dragon, a lake and a maze are tough, think about the difficulties of overcoming homelessness. BoMF’s mission is to revolutionize the way our society approaches homelessness. Their unique running-based model demonstrates that if an indivudual first restores confidence, strength and self-esteem, they are better equipped to tackle the road ahead and move toward jobs, homes and new lives. BoMF provides practical training and employment resources for achieving independence, an environment that promotes accountability, and a community that offers compassion and hope for all in need.", CharityName = "Back on My Feet (BoMF)", Distance = 4.0, Title = "Eternal Glory 4 Miler" },
                        new { RaceId = 27, CharityDescription = "ASOC is a global network of conservation organizations seeking to preserve the world’s last great wilderness, which belongs to all humankind. ASOC’s mission is to protect the Antarctic and Southern Ocean’s unique and vulnerable ecosystems by speaking for Antarctica and its magnificent species, from the tiniest krill to the largest blue whales.", CharityName = "Antarctic & Southern Ocean Coalition (ASOC)", Distance = 6.06, Title = "Platform 9 3/4k Year Four" },
                        new { RaceId = 28, CharityDescription = "The Quidditch Challenge supports all 2017 charity partners, with proceeds from this medal being divided evenly amongst them!", CharityName = "HRC 2017 Charity Partners", Distance = 3.1, Title = "Quidditch Challenge" },
                        new { RaceId = 29, CharityDescription = "BC/EFA helps men, women and children across the country and across the street receive lifesaving medications, health care, nutritious meals, counseling and emergency financial assistance. In the ultimate example of Transfiguration in the Muggle World, they turn love into money…and then turn money into love.", CharityName = "Broadway Cares/Equity Fights AIDS (BC/EFA)", Distance = 5.6, Title = "Nargle 9k" },
                        new { RaceId = 30, CharityDescription = "Many young people face an uncertain future simply because they are growing up in poverty. By the age of seven, children growing up in poverty are more than twice as likely as their better-off peers to be behind on expected reading levels. By the time they are in their teens, 60 percent won’t get the grades needed to go on to college or get employment after graduation. Debate Mate seeks to reverse that trend by using the power of debate to give disadvantaged young people the skills they need to become exceptional young leaders – confidence, interpersonal communication skills and higher order thinking. While starting in the UK, Debate Mate now enjoys a strong global presence, operating programs in Nepal, Africa, Jamaica, the Middle East, and the United States. They believe that every child deserves equal access to a top education, and wants the youth of today to find their voice so that they can become the leaders of tomorrow.", CharityName = "Debate Mate", Distance = 3.1, Title = "DA 5k" },
                        new { RaceId = 31, CharityDescription = "All Coalition members work to keep immigrant children and families safe and together. This is a huge undertaking, since most anti-immigrant actions affect not just individuals, but also their family members. Through the Coalition’s ‘Keeping Families Together Initiative’, members provide immigration-related services such as legal and social services to immigrants and their families.", CharityName = "Hispanic Federation and Lin-Manuel Miranda’s Immigrants: We Get the Job Done Coalition - Keeping Families Together Initiative", Distance = 3.1, Title = "Forgotten 5k" },
                        new { RaceId = 32, CharityDescription = "Toucan Rescue Ranch (TRR) focuses on the care, rehabilitation and study of Costa Rican wildlife including toucans, owls and sloths! TRR receives and cares for confiscated, sick and injured animals and then gives them a loving home with the goal of providing appropriate medical treatment, rehabilitation and then, when possible, returning them to their natural environment. HRC’s goal was to fully fund a brand new sloth rescue/reception facility in northern Costa Rica. Goats of Anarchy (GOA) is the passion of Leanne Lauricella, who left behind a successful career in New York City and has now created a sanctuary for goats with special needs, teaching the world acceptance and inclusion and inspiring others to “fight like a goat”! Specifically, HRC funded critical fencing and other important infrastructure improvements at GOA’s new facility in New Jersey.", CharityName = "Toucan Rescue Ranch and Goats of Anarchy", Distance = 13.1, Title = "Half-Giant Half Marathon" },
                        new { RaceId = 33, CharityDescription = "All Star Code is a nonprofit computer science education organization focused on giving young, intelligent, driven men of color access to the necessary skills so they can be part of the growing tech world. HRC’s goal was to help All Star Code fund an entire “cohort” of 20 young men of color so they can complete the Summer Intensive Program in 2019.", CharityName = "All Star Code", Distance = 6.2, Title = "Royal 10k" },
                        new { RaceId = 34, CharityDescription = "RODS’ mission is simple. They promote the adoption of orphans with Down syndrome by raising adoption grant funds, one child at a time, and by participating in organized, athletic races and awareness events. They literally run for orphans! The funds they raise cover a large portion of the expense to get children from orphanages in the developing world to forever homes in the US and Canada. Based on the Headmaster’s arithmancy, this event set out to fund seven fantastic kids, and vastly improve their odds of adoption.", CharityName = "RODS – Racing for Orphans with Down Syndrome", Distance = 6.2, Title = "Platform 9 3/4k Year Five" },
                        new { RaceId = 35, CharityDescription = "The Phoenix Challenge supports all 2017 charity partners, with proceeds from this medal being divided evenly amongst them!", CharityName = "HRC 2018 Charity Partners", Distance = 3.1, Title = "Phoenix Challenge" }
                    );
                });

            modelBuilder.Entity("HogwartsRunningClub.Models.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("HouseExclusive");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(65);

                    b.Property<int>("TopicCategoryId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("TopicId");

                    b.HasIndex("TopicCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Topic");

                    b.HasData(
                        new { TopicId = 1, Content = "There is a rumor going around that once JK finishes writing the Fantastic Beasts Scripts, she will begin writing adult Potter novels! The rumor also claims that it will pretain to Harry being an Auror, Cursed Child being retconned, and somehow tie into the Fantastic Beast series. I believe that something may be going on with the whole obscurus/voldemort connection!", DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HouseExclusive = false, Title = "J.K. Rowling to pen Adult Potter Novels!?", TopicCategoryId = 10, UserId = "2985541a-36e1-4172-aa7d-ef2645a46b32" },
                        new { TopicId = 2, Content = "This is the only thing that makes sense! Discuss!", DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), HouseExclusive = true, Title = "Aruleus Dumbledore is the Obscurus or Ariana!", TopicCategoryId = 2, UserId = "2985541a-36e1-4172-aa7d-ef2645a46b32" }
                    );
                });

            modelBuilder.Entity("HogwartsRunningClub.Models.TopicCategory", b =>
                {
                    b.Property<int>("TopicCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .IsRequired();

                    b.HasKey("TopicCategoryId");

                    b.ToTable("TopicCategory");

                    b.HasData(
                        new { TopicCategoryId = 1, Label = "General" },
                        new { TopicCategoryId = 2, Label = "Lore" },
                        new { TopicCategoryId = 3, Label = "Charity" },
                        new { TopicCategoryId = 4, Label = "Races" },
                        new { TopicCategoryId = 5, Label = "Fitness" },
                        new { TopicCategoryId = 6, Label = "Personal" },
                        new { TopicCategoryId = 7, Label = "Humor" },
                        new { TopicCategoryId = 8, Label = "Books" },
                        new { TopicCategoryId = 9, Label = "Movies" },
                        new { TopicCategoryId = 10, Label = "Rumors" }
                    );
                });

            modelBuilder.Entity("HogwartsRunningClub.Models.UserRace", b =>
                {
                    b.Property<int>("UserRaceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RaceBib");

                    b.Property<string>("RaceBibImage");

                    b.Property<int>("RaceId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("UserRaceId");

                    b.HasIndex("RaceId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRace");

                    b.HasData(
                        new { UserRaceId = 1, RaceId = 1, UserId = "2985541a-36e1-4172-aa7d-ef2645a46b32" },
                        new { UserRaceId = 2, RaceId = 2, UserId = "2985541a-36e1-4172-aa7d-ef2645a46b32" },
                        new { UserRaceId = 3, RaceId = 3, UserId = "2985541a-36e1-4172-aa7d-ef2645a46b32" },
                        new { UserRaceId = 4, RaceId = 4, UserId = "2985541a-36e1-4172-aa7d-ef2645a46b32" },
                        new { UserRaceId = 5, RaceId = 5, UserId = "2985541a-36e1-4172-aa7d-ef2645a46b32" },
                        new { UserRaceId = 6, RaceId = 6, UserId = "2985541a-36e1-4172-aa7d-ef2645a46b32" }
                    );
                });

            modelBuilder.Entity("HogwartsRunningClub.Models.Workout", b =>
                {
                    b.Property<int>("WorkoutId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<double>("Distance");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("WorkoutId");

                    b.HasIndex("UserId");

                    b.ToTable("Workout");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("HogwartsRunningClub.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("DateRegistered")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<int?>("HouseId");

                    b.Property<string>("ImagePath");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Location");

                    b.Property<double>("MilesRun");

                    b.Property<string>("PotterName")
                        .IsRequired();

                    b.HasIndex("HouseId");

                    b.ToTable("ApplicationUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new { Id = "2985541a-36e1-4172-aa7d-ef2645a46b32", AccessFailedCount = 0, ConcurrencyStamp = "729df9d5-f548-4885-8062-c7451e70f880", Email = "admin@admin.com", EmailConfirmed = true, LockoutEnabled = false, NormalizedEmail = "ADMIN@ADMIN.COM", NormalizedUserName = "ADMIN@ADMIN.COM", PasswordHash = "AQAAAAEAACcQAAAAEDvp3MUYd7FQAbilY+U1LOstaIdkvqFqxgmbDZUmOQqKmE1PuQHhU7F2ALvaLKVwog==", PhoneNumberConfirmed = false, SecurityStamp = "4414c7ff-b04c-4a5e-91c3-f0369c6d5693", TwoFactorEnabled = false, UserName = "admin@admin.com", DateRegistered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), FirstName = "admin", LastName = "admin", Location = "Nashville, TN", MilesRun = 134.8, PotterName = "Admina Straytor" }
                    );
                });

            modelBuilder.Entity("HogwartsRunningClub.Models.Comment", b =>
                {
                    b.HasOne("HogwartsRunningClub.Models.Topic", "Topic")
                        .WithMany("Comments")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HogwartsRunningClub.Models.ApplicationUser", "User")
                        .WithMany("UserComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HogwartsRunningClub.Models.Topic", b =>
                {
                    b.HasOne("HogwartsRunningClub.Models.TopicCategory", "TopicCategory")
                        .WithMany("Topics")
                        .HasForeignKey("TopicCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HogwartsRunningClub.Models.ApplicationUser", "User")
                        .WithMany("UserTopics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HogwartsRunningClub.Models.UserRace", b =>
                {
                    b.HasOne("HogwartsRunningClub.Models.Race", "Race")
                        .WithMany("RaceParticipants")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HogwartsRunningClub.Models.ApplicationUser", "User")
                        .WithMany("UserRaces")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HogwartsRunningClub.Models.Workout", b =>
                {
                    b.HasOne("HogwartsRunningClub.Models.ApplicationUser", "User")
                        .WithMany("UserWorkouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HogwartsRunningClub.Models.ApplicationUser", b =>
                {
                    b.HasOne("HogwartsRunningClub.Models.House", "House")
                        .WithMany("HouseUsers")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
